spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distributed-task
    username: distributed-task
    password: distributed-task
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      data-source-properties:
        rewriteBatchedStatements: true
        useConfigs: maxPerformance
      validation-timeout: 10000
      keepalive-time: 60000
      connection-timeout: 10000
  application:
    name: test-app

distributed-task:
  enabled: true
  saga:
    enabled: true
    # Common properties for library.
    common:
      # Cache expiration for internal purpose
      cache-expiration: PT30S
      # Fixed delay to scan deprecation sagas: completed and expired.
      deprecated-saga-scan-fixed-delay: PT10S
      # The size of batch of expired saga entities in db to handle (remove) in one tick.
      expired-saga-batch-size-to-remove: 1000
    # Properties to configure saga statistics.
    saga-stat-properties:
      # Top N saga names to print in stat.
      top-n-sagas: 5
      # Initial delay between calculation of saga statistics.
      calc-initial-delay: PT1S
      # Delay between calculation of saga statistics.
      calc-fixed-delay: PT10S
    # Whole saga configuration by name
    saga-properties-group:
      # Default properties for any saga.
      default-saga-properties:
        # Time between completion of saga and removing of its result from db.
        available-after-completion-timeout: PT1M
        # After timeout expired, the whole saga will be canceled.
        expiration-timeout: PT10M
        # If any revert operation fail, then stop execute reverting chain and complete saga.
        stop-on-failed-any-revert: false
      # Custom properties for particular saga by name.
      saga-properties-group:
        # Saga name
        test:
          expiration-timeout: PT3M
    # Configuration for saga methods
    saga-method-properties-group:
      # Default configuration for all methods,
      # override default configuration for tasks from task-properties-group#default-properties
      default-saga-method-properties:
        # @Transactional can be used instead
        execution-guarantees: AT_LEAST_ONCE
        retry:
          fixed:
            delay: PT1S
            max-interval: PT5S
            max-number: 5
          retry-mode: FIXED
        max-parallel-in-cluster: 100
        timeout: PT10M
      # Customisation of configuration for dedicated saga method
      saga-method-properties:
        # Saga method name
        addition_v0:
          retry:
            fixed:
              delay: PT1S
              max-interval: PT5S
              max-number: 5
            retry-mode: FIXED
          max-parallel-in-cluster: 100
          timeout: PT10M
        deleteLocal:
          retry:
            fixed:
              delay: PT1S
              max-interval: PT5S
              max-number: 5
            retry-mode: FIXED
          max-parallel-in-cluster: 100
          timeout: PT10M
        createOnRemoteServiceOne:
          retry:
            fixed:
              delay: PT1S
              max-interval: PT5S
              max-number: 5
            retry-mode: FIXED
          max-parallel-in-cluster: 100
          timeout: PT10M
        createOnRemoteServiceOne_v2:
          retry:
            fixed:
              delay: PT1S
              max-interval: PT5S
              max-number: 5
            retry-mode: FIXED
          max-parallel-in-cluster: 100
          timeout: PT10M